name: customer-churn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scikit-learn>=1.2.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - plotly>=5.11.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - ipykernel>=6.19.0
  - pip
  - pip:
    - shap>=0.41.0
    - streamlit>=1.25.0
    - joblib>=1.2.0
    - pyyaml>=6.0
    - black>=23.0.0
    - flake8>=6.0.0
    - pytest>=7.2.0

